<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php $_source  = $this->getSource() ?>
<?php if ($_source): ?>
    <?php $amount = $this->geMozgPaymentInvoiceFeeAmount(); ?>
    <?php if ($amount !== null): ?>
        <tr>
            <td class="label"><?php echo $this->getMozgPaymentFeeInvoiceFeeLabel() ?></td>
            <td><input type="text" name="creditmemo[mozg_fee_payment_fee_refund]" value="<?php echo $amount; ?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="mozg_fee_payment_fee_refund" /></td>
        </tr>
        <tr>
            <td colspan="2"><div id="mozg_fee_payment_fee_refund_adv"></div></td>
        </tr>

        <script type="text/javascript">
            //<![CDATA[
            Validation.addAllThese([
                ['not-negative-amount', '<?php echo $this->helper('mozg_fee')->__('Please enter a positive number in this field.') ?>', function(v) {
                    if(v.length)
                        return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                    else
                        return true;
                }]
            ]);

            if ($('mozg_fee_payment_fee_refund')) {
                $('mozg_fee_payment_fee_refund').advaiceContainer = $('mozg_fee_payment_fee_refund_adv');
                unblockMozgSubmit('mozg_fee_payment_fee_refund');
            }

            function unblockMozgSubmit(id) {
                $(id).observe('focus', function(event) {
                    if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                        enableElements('submit-button');
                    }
                });
            }
            //]]>
        </script>

    <?php endif; ?>
<?php endif; ?>
